### ISSUE TITLE
Tie count wrong in PokerStove?

### ISSUE THREAD

**Issue by CheeseBallz2** [andrewprock/pokerstove#16]
Hi Andrew

I am running PokerStove version 1.24.
I picked pre-flop hands:  Player 1 = Jc5c, and Player 2 = QdTd, and evaluated using Enumerate All.
The results are these:

Text results appended to pokerstove.txt

1,712,304 games     0.015 secs  114,153,600 games/sec

Board: 
Dead:  

```
equity  win     tie           pots won  pots tied   
```

Hand 0:     35.525%     35.06%  00.46%          600384       7911.00   { Jc5c }
Hand 1:     64.475%     64.01%  00.46%         1096118       7911.00   { QdTd }

However, 600384 + 1096118 + 2*7911.00 doesn't add up to 1,712,304.
The win/loss are correct, but ties should be 7901.00, not 7911.00.

**Comment by andrewprock** [comment]
it's a feature, it reports shares, not the number of ties.
