### ISSUE TITLE
64 bit compatibility Issue

### ISSUE THREAD

**Issue by markwillowtree** [andrewprock/pokerstove#18]
Hi Andrew,

When I run the following code in window/linux it produces different results.

```
set<CardSet> pockets = createCardSet(4, Card::SUIT_CANONICAL);

for (auto pit = pockets.begin(); pit != pockets.end(); pit++)
{
    cout << pit->str() << "\n";
}
```

On Linux this is the last cardset in the list

"AcAdAhAs"

On windows it's 

"AcAd2c2c"

I've set the "TARGET_MACHINE" to x86 for penum, peval and ps-lut. (I modified main.cpp in ps-lut and added above code). I'm also definitely pointing to the lib32 version of boost.

I guess that one of the constants used as a mask is wrong somewhere? Or is there another setting I'm missing? I noticed that Windows doesn't recognise the -m32 and /m32 compiler/linker options.

I'll be working in linux from now on, but it might be worth flagging this up as an issue for other x64 users.

Thanks

Mark

**Comment by andrewprock** [comment]
Please post this to the issues on github so it doesn't get forgotten.

Thanks,

- Andrew


Sent on my Virgin Mobile Samsung Galaxy S® 5


-------- Original message --------

**Comment by andrewprock** [comment]
I don't think there are any guarantees about the order that the cards are produced.  Can you reproduce the bug with just two cards?  Do the lists contain the same sets of cards?  With the same suits?
