### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by thomaxxl** [andrewprock/pokerstove#24]
Hi,

I had to change some makefiles to get pokerstove compiled: 
added -std=c++11 to CMAKE_CXX_FLAGS in ./src/lib/pokerstove/penum/CMakeLists.txt

and -lpthread to ./CMakeFiles/util_tests.dir/link.txt

**Comment by andrewprock** [comment]
Please add a push request and I will check it out.

**Comment by azyr** [comment]
In addition to what @thomaxxl mentioned I needed to put that -std=c++11 also in CMakeLists.txt files in peval and util as well.

So to sum it up, the following changes are neccessary to get the newest commit (0f057ff5168d18754dfda154f4715281f8a678ee) to compile:

Add -std=c++11 in CMAKE_CXX_FLAGS in following files:
- ./src/lib/pokerstove/penum/CMakeLists.txt
- ./src/lib/pokerstove/penum/CMakeLists.txt
- ./src/lib/pokerstove/util/CMakeLists.txt

After that run cmake and make. It will stop on error when trying to build the testkit (undefined reference to some pthread stuff). So at that point you need to modify the compiled file in {build_dir}/lib/pokerstove/util/CMakeFiles/util_tests.dir/link.txt and add -lpthread in the end. Now run make again and it should compile.

I could add a push request but I'm not sure how to address the problem with googletest properly.

**Comment by Pretenderr** [comment]
Add -std=c++11 in CMAKE_CXX_FLAGS in following files:
./src/lib/pokerstove/peval/CMakeLists.txt

**Comment by scraggelz** [comment]
These were very helpful seeing as the -std=c++11 and lpthread were giving me trouble when compiling. Thanks.
