### ISSUE TITLE
Googletest svn no longer exists

### ISSUE THREAD

**Issue by flocks** [andrewprock/pokerstove#29]
Googletest svn seems to no longer exist. So I had to use a mirror of it hosted on github: https://github.com/stp/googletest

So I had to replace in _src/ext/gtest/CMakeLists.txt_
`SVN_REPOSITORY http://googletest.googlecode.com/svn/trunk` by `GIT_REPOSITORY https://github.com/stp/googletest` 

Also I had to add `-lpthread -std=c++11` in order to compile the project in the following files
- src/lib/pokerstove/penum/CMakeLists.txt
- src/lib/pokerstove/peval/CMakeLists.txt
- src/lib/pokerstove/util/CMakeLists.txt

Hope it will be helpful.

**Comment by andrewprock** [comment]
vendor'd
