### ISSUE TITLE
Can't compile pokerstove as a drop-in library

### ISSUE THREAD

**Issue by sbarratt** [andrewprock/pokerstove#30]
I'm trying to include pokerstove in a c++ project. I'm on mac, and am having trouble compiling and including the files in my project.

I'm running the default program you have in the peval documentation and running the following command to compile it:

`> g++ peval_helloworld.cpp -I pokerstove/src/lib/`

Here's the error:

```
peval_helloworld.cpp:11:23: error: invalid use of incomplete type 'pokerstove::Card'
    CardSet big_slick(Card(Rank('A'),Suit('s')),
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
pokerstove/src/lib/pokerstove/peval/Rank.h:117:18: note: forward declaration of 'pokerstove::Card'
    friend class Card;
                 ^
peval_helloworld.cpp:12:23: error: invalid use of incomplete type 'pokerstove::Card'
                      Card(Rank('K'),Suit('s')));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
pokerstove/src/lib/pokerstove/peval/Rank.h:117:18: note: forward declaration of 'pokerstove::Card'
    friend class Card;
                 ^
2 errors generated.
```

And the code:

```
#include <iostream>
#include <pokerstove/peval/CardSet.h>

using pokerstove::CardSet;
using pokerstove::Card;
using pokerstove::Rank;
using pokerstove::Suit;

int main(void)
{
    CardSet big_slick(Card(Rank('A'),Suit('s')),
                      Card(Rank('K'),Suit('s')));
    std::cout << big_slick.str() << std::endl;

    CardSet dead_mans_hand("AcAs8d8hJs");
    std::cout << dead_mans_hand.str() << std::endl;
}
```

**Comment by frankh** [comment]
I managed to get this working, but I'm not an expert at C++ so it might not be the best way.

There are a few problems I found, first, there's not constructor for passing in Cards like that and if there was you would need to include `Card.h` `Rank.h` `Suit.h` too.

You also aren't compiling any of the .cpp files, so there's nothing to link to.

It also tries to include Config.h, which is created by cmake. After running cmake you need to add `-I pokerstove/src/build/`.

Finally, you need to either delete all the `.test.cpp` files, or include the gtest headers as well

If you delete the test.cpp files, the following command should work

```
g++ peval_helloworld.cpp pokerstove/src/lib/pokerstove/peval/*.cpp -I pokerstove/src/lib/ -I pokerstove/src/build/
```

**Comment by andrewprock** [comment]
removed Config.h mess
