### ISSUE TITLE
Arguments for ps-eval are ignored

### ISSUE THREAD

**Issue by ottopotto** [andrewprock/pokerstove#32]
I compiled the latest master branch version e508a76810 on Ubuntu 16.04, AMD64, and ran the following commands:
`$ ./ps-eval AcAh`
`$ ./ps-eval --help`
On both times the program first printed this:

```
The whole deck has 52 cards
There are 1326 two card combinations
There are 1 two card combinations
```

Then the program ran for ~8 minutes and finally printed:

```
A random hand has 40.0942 % equity (804780676 36223609 0 0)
The hand As6s has 59.9058 % equity (1220344506 36223609 0 0)
```

It looked like any arguments or no arguments would have had the same effect, although I didn't wait for the program to finish on other times.

**Comment by jaak-s** [comment]
I've checked the code and the current `ps-eval` does not take any arguments and only computes fixed matchup (any-two vs As6s). If there is interest I can create a fork that has can perform basic hand-to-hand comparisons. Let me know.

**Comment by ottopotto** [comment]
Thanks for finding the problem! I think the ps-eval version described in README.md would be a good example and also useful on its own for some. But I don't know why it has been modified. It would be nice if README.md was updated. I'm not currently planning to use this library so I don't need this at this point.

**Comment by jaak-s** [comment]
Yeah, it seems the REAMDE.md is outdated. In any case, if someone is interested, I've a modified version that can do basic evaluations.

**Comment by KaiSteinert** [comment]
Some examples that show basic functionality would be appreciated.

**Comment by jaak-s** [comment]
@KaiSteinert As I commented before, this pokerstove version does not do any hand-to-hand comparison (only a fixed all-hands vs As6s). I've a personal version where `ps-eval` does that. If you are interested I can make it available on github and you can use it.

**Comment by mikefore** [comment]
@jaak-s Hi, I would be interested in a working pokerstove version. It would be really great if you could upload it on github. Thanks for taking the time and correcting this error.

**Comment by jdoerrie** [comment]
I implemented a version of ps-eval that respects it's command line arguments and created a pull request (#37). Feel free to check it out :) It now simply calls the existing APIs, but this already makes it much more useful.

**Comment by andrewprock** [comment]
fixed
