### ISSUE TITLE
Can you please release the command line version of PokerStove?

### ISSUE THREAD

**Issue by tiltmine** [andrewprock/pokerstove#40]
The ps-eval script is missing a lot of functionality like expandable ranges, board and dead cards.

Through some research it appears that this already exists:
> Yes there is, but it is not currently available for general distribution. If you are interested in purchasing it, send me email and I'll consider your situation.The price for the command line version is $300

Has this been released? I just tried running PokerStove.exe on command line and don't see any options, the GUI just pops up.

Thanks!

**Comment by Murukaen** [comment]
+1

**Comment by andrewprock** [comment]
It's open source, feel free to submit a patch.
