### ISSUE TITLE
ShowdownEnumerator: Break and return result after X iterations

### ISSUE THREAD

**Issue by Vingtoft** [andrewprock/pokerstove#43]
Calculating the equity for multiple random hands takes a very long time.
If I'm not mistaken, the `ShowdownEnumerator` calculates _all_ possible outcomes of hands, resulting in billions of calculations. It would be possible to limit the calculations to, say, 5% (and probably less than that) and get a result thats very close to the absolute result. 
This would result in a major performance improvement.

**Question: How can this functionality be implemented in ShowdownEnumerator?**

**Comment by andrewprock** [comment]
Won't do, we'll need monte carlo to get it right.
