### ISSUE TITLE
Delete this

### ISSUE THREAD

**Issue by elgatoblanco3** [andrewprock/pokerstove#44]
Hi guys, I just registered to this site to ask you for a 169x169 Matrix of the preflop equities every hand vs every hand. I'm very sorry if this is the wrong section. I'm googling for several hours now. There used to be a link to what I need (http://www.pokerstove.com/analysis/preflopeq.php), but it's down. I hope someone can help me out. You'd save my life!

**Comment by andrewprock** [comment]
Should be available on archive.org
