### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by RayKMAllen** [andrewprock/pokerstove#62]
Hi Andrew (and co),

Thanks for all your work making this available. I've been trying to get it up and running on a Windows 10 PC and am running into an issue while building in Visual Studio.
The error I get is LNK1104: cannot open 'peval.lib'. I'm a novice to C++, have been searching all day for a fix but no joy. I can see peval.lib under Linker -> Input -> Additional Dependencies.
What am I doing wrong?

Thanks
Ray

**Comment by hughfuve** [comment]
I'm getting the same issue, my guess is that we have to build it somehow. by compiling it ourselves inside that /src/lib/pokerstove/peval folder

**Comment by tsssp** [comment]
I'm getting the same issue too.
