### ISSUE TITLE
ps-eval hangs when no board present

### ISSUE THREAD

**Issue by ncp1113** [andrewprock/pokerstove#68]
On the command line ps-eval hangs. For example
ps-eval --hand AcAd
just hangs but 
ps-eval --hand AcAd --board AhTcTh
provides output:
The hand AcAd has 99.4682 % equity (1064004 495 0 0)
A random hand has 0.531775 % equity (5196 495 0 0)

Linux version 4.19.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)

**Comment by wesley-stone** [comment]
I found that it actually did plenty of computation and finally outputs a strength of the given two cards.

**Comment by ncp1113** [comment]
I am running it from the build/bin directory. I tried it on a MacBook Pro running Catalina and I got the same problem. The ps-eval I am using was downloaded on Feb 23.
./ps-eval AhTh hangs
./ps-eval AhTh --board AsTs9h
The hand AhTh has 89.3639 % equity (953709 2654 0 0)
A random hand has 10.6361 % equity (111173 2654 0 0)

**Comment by wesley-stone** [comment]
did you check the cpu usage？I ran on ubuntu16.04 and wait for a while and then it printed the rate

**Comment by ncp1113** [comment]
It is using almost 100% of CPU. I will let it run in a separate terminal to see if it ever finishes.

**Comment by wesley-stone** [comment]
I think it is reasonable because when you do not give exact board configuration, the program will iterate for every possible public card combinations among the remaining cards.

**Comment by ncp1113** [comment]
I see. I will mark this closed. Thanks for your insight.
