### ISSUE TITLE
Could not find gtest using the following names

### ISSUE THREAD

**Issue by tandriamirado** [andrewprock/pokerstove#73]
Good day,

Can't build it..
Debian testing, kernel 5.10.0-1-686 #1 SMP Debian 5.10.4-1 (2020-12-31) i686 GNU/Linux

`$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:18 (find_library):
  Could not find gtest using the following names:

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/pokerstove/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/pokerstove/build/CMakeFiles/CMakeError.log".
`
See also attached '/usr/local/src/pokerstove/build/CMakeFiles/CMakeError.log'
[CMakeError.log](https://github.com/andrewprock/pokerstove/files/5877372/CMakeError.log)

'libpthread-stubs0-dev' is installed:

`
$ apt policy libpthread-stubs0-dev
libpthread-stubs0-dev:
  Installé : 0.4-1
  Candidat : 0.4-1
 Table de version :
 *** 0.4-1 500
        500 http://deb.debian.org/debian testing/main i386 Packages
        100 /var/lib/dpkg/status
`
What can I try now?
Thanks in advance ;)

**Comment by RubenK77** [comment]
Same issue on manjaro

**Comment by xgshark** [comment]
same issue on Ubuntu 20

**Comment by andrewprock** [comment]
I think this is working now.
