### ISSUE TITLE
cmake doesn't find googletest

### ISSUE THREAD

**Issue by mitchblank** [andrewprock/pokerstove#74]
I'm investigating why the homebrew formula for pokerstove is having build problems.  The code in pokerstove does:
```
add_subdirectory(src/ext/googletest)
find_library(gtest REQUIRED)
```
... I'm not sure if `find_library` that will ever find the local copy or if this assumes that it's in /usr/lib?  Or maybe it worked on older versions of cmake but broke more recently?

Anyway when running `cmake` 3.19.4 I am seeing:
```
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:18 (find_library):
  Could not find gtest using the following names:


-- Configuring incomplete, errors occurred!
```

As a workaround I am just going to switch to `find_package` and use homebrew's own copy of googletest.  With this it seems to build fine.

**Comment by andrewprock** [comment]
This should be resolved now.
